### ISSUE TITLE
Two "frida-server" processes 

### ISSUE THREAD

**Issue by russellchek** [ViRb3/magisk-frida#19]
Just wondering if this is normal when I run "frida-ps -U" i see two "frida-server" processes running.

**Comment by ViRb3** [comment]
No, you shouldn't see two "frida-server" processes. Could the other one be from a different Magisk module/manual installation?

**Comment by Manouchehri** [comment]
Is one a zombie process? I think I might have seen this in the past too.

**Comment by enovella** [comment]
Can you show which processes are you talking about?  Are you referring to frida-helper or frida-server?

**Comment by ViRb3** [comment]
This was most likely introduced by a bug in db63dc26d033d2c13309b5d0de987da3e61d637d, where the daemon would be restarted infinitely every 1 second. This has now been fixed in [15.1.14-4](https://github.com/ViRb3/magisk-frida/releases/tag/15.1.14-4) (d0eee42cb42332995c5b20f6a8e7ab3c8d5afb76). For more info: https://github.com/ViRb3/magisk-frida/pull/18#issuecomment-1022079368
